version: "3.0"
services:
  node:
    build: .
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"
    command: "pm2-runtime start ecosystem.config.js"